name: Deploy Storybook to Github pages

on:
  release:
    types: [published]

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 18

      - run: yarn
      - run: yarn build-storybook
      - run: touch storybook-static/.nojekyll

      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: docs
          FOLDER: storybook-static
