name: Publish to npm

on:
  release:
    types: [published]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          cache: yarn

      - run: yarn
      - run: npm version --new-version "${{github.ref_name}}" --no-git-tag-version

      - name: Commit version bump
        uses: EndBug/add-and-commit@v7
        with:
          add: ./package.json
          message: "ci(deploy): bump version to ${{github.ref_name}} 🚀"
          branch: main

      - run: yarn build && npm pack
      - run: npm publish --access public nathanpb-react-plotly-${{github.ref_name}}.tgz
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
